import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { ethers, network, run } from 'hardhat';
import { BaseContract, ContractTransactionReceipt, ZeroAddress } from 'ethers';

type DeploymentRecord = {
  name: string;
  address: string;
  txHash: string;
  blockNumber: number;
  verified: boolean;
};

const DRY_RUN = process.argv.includes('--dry-run');
const MAX_GAS_0G = 0.3;

async function waitReceipt(contract: BaseContract): Promise<ContractTransactionReceipt> {
  const tx = contract.deploymentTransaction();
  if (!tx) throw new Error(`Missing deployment tx for ${await contract.getAddress()}`);
  const receipt = await tx.wait(2);
  if (!receipt) throw new Error(`Missing receipt for ${tx.hash}`);
  return receipt;
}

async function deploy(name: string, args: readonly unknown[]): Promise<{ contract: BaseContract; record: DeploymentRecord; args: readonly unknown[] }> {
  const factory = await ethers.getContractFactory(name);
  const contract = await factory.deploy(...args);
  await contract.waitForDeployment();
  const receipt = await waitReceipt(contract);
  const address = await contract.getAddress();
  console.log(`  ✓ ${name}: ${address}`);
  return { contract, args, record: { name, address, txHash: receipt.hash, blockNumber: receipt.blockNumber, verified: false } };
}

async function verify(record: DeploymentRecord, args: readonly unknown[]): Promise<DeploymentRecord> {
  try {
    await run('verify:verify', { address: record.address, constructorArguments: [...args] });
    return { ...record, verified: true };
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    if (msg.toLowerCase().includes('already verified')) return { ...record, verified: true };
    console.error(`  ✗ Verification failed for ${record.name}: ${msg}`);
    return record;
  }
}

async function writeContractsLib(aristotleRecords: DeploymentRecord[]): Promise<void> {
  let galileoRecords: DeploymentRecord[] = [];
  try {
    const raw = await readFile(join(process.cwd(), 'deployments', 'galileo.json'), 'utf8');
    galileoRecords = JSON.parse(raw) as DeploymentRecord[];
  } catch {}

  const toObj = (records: DeploymentRecord[]): Record<string, string> =>
    Object.fromEntries(records.map(r => [r.name, r.address]));

  const g = toObj(galileoRecords);
  const a = toObj(aristotleRecords);

  const content = `// Auto-generated by deploy-aristotle.ts — do not edit manually
// Regenerate: pnpm -F @apogee/contracts deploy:aristotle

export type NetworkContracts = {
  PolicyEngine: string;
  ReceiptBook: string;
  AgentIdentity: string;
  ServiceRegistry: string;
  RevenueSplitter: string;
  PaymentRouter: string;
  EscrowVault: string;
  AccountFactory: string;
  AgentAccount: string;
};

const GALILEO: NetworkContracts = {
  PolicyEngine:    '${g['PolicyEngine'] ?? ''}',
  ReceiptBook:     '${g['ReceiptBook'] ?? ''}',
  AgentIdentity:   '${g['AgentIdentity'] ?? ''}',
  ServiceRegistry: '${g['ServiceRegistry'] ?? ''}',
  RevenueSplitter: '${g['RevenueSplitter'] ?? ''}',
  PaymentRouter:   '${g['PaymentRouter'] ?? ''}',
  EscrowVault:     '${g['EscrowVault'] ?? ''}',
  AccountFactory:  '${g['AccountFactory'] ?? ''}',
  AgentAccount:    '${g['AgentAccount'] ?? ''}',
};

const ARISTOTLE: NetworkContracts = {
  PolicyEngine:    '${a['PolicyEngine'] ?? ''}',
  ReceiptBook:     '${a['ReceiptBook'] ?? ''}',
  AgentIdentity:   '${a['AgentIdentity'] ?? ''}',
  ServiceRegistry: '${a['ServiceRegistry'] ?? ''}',
  RevenueSplitter: '${a['RevenueSplitter'] ?? ''}',
  PaymentRouter:   '${a['PaymentRouter'] ?? ''}',
  EscrowVault:     '${a['EscrowVault'] ?? ''}',
  AccountFactory:  '${a['AccountFactory'] ?? ''}',
  AgentAccount:    '${a['AgentAccount'] ?? ''}',
};

export const CONTRACTS: Record<number, NetworkContracts> = {
  16602: GALILEO,
  16661: ARISTOTLE,
};

export const EXPLORER_URLS: Record<number, string> = {
  16602: 'https://chainscan-galileo.0g.ai',
  16661: 'https://chainscan.0g.ai',
};

export const CHAIN_NAMES: Record<number, string> = {
  16602: 'Galileo (testnet)',
  16661: 'Aristotle (mainnet)',
};

export const RPC_URLS: Record<number, string> = {
  16602: 'https://evmrpc-testnet.0g.ai',
  16661: 'https://evmrpc.0g.ai',
};

export function getContracts(chainId: number): NetworkContracts {
  const c = CONTRACTS[chainId];
  if (!c) throw new Error(\`No contract addresses for chainId \${chainId}\`);
  return c;
}

export const CONTRACT_NAMES = Object.keys(GALILEO) as (keyof NetworkContracts)[];
`;

  const webLibPath = resolve(process.cwd(), '..', '..', 'apps', 'web', 'src', 'lib', 'contracts.ts');
  await mkdir(dirname(webLibPath), { recursive: true });
  await writeFile(webLibPath, content);
  console.log(`  ✓ Wrote ${webLibPath}`);
}

async function dryRun(): Promise<void> {
  if (network.config.chainId !== 16661) {
    throw new Error('Dry run targets Aristotle (chainId 16661). Use --network aristotle.');
  }
  console.log('\n=== ARISTOTLE DRY RUN — estimating deploy gas ===\n');

  const [deployer] = await ethers.getSigners();
  if (!deployer) throw new Error('No signer configured.');

  const feeData = await ethers.provider.getFeeData();
  const gasPrice = feeData.gasPrice ?? 1_000_000_000n;

  const specs: Array<[string, readonly unknown[]]> = [
    ['PolicyEngine',    [deployer.address]],
    ['ReceiptBook',     [deployer.address]],
    ['AgentIdentity',   [deployer.address]],
    ['ServiceRegistry', [deployer.address]],
    ['RevenueSplitter', [deployer.address]],
    ['PaymentRouter',   [deployer.address, ZeroAddress, ZeroAddress]],
    ['EscrowVault',     [deployer.address, ZeroAddress]],
    ['AccountFactory',  [deployer.address, ZeroAddress, ZeroAddress]],
  ];

  let totalGas = 0n;
  for (const [name, args] of specs) {
    const factory = await ethers.getContractFactory(name);
    const deployTx = await factory.getDeployTransaction(...args);
    const gasEst = await ethers.provider.estimateGas(deployTx);
    const cost = Number(gasEst * gasPrice) / 1e18;
    console.log(`  ${name.padEnd(20)} ${gasEst.toLocaleString().padStart(12)} gas = ${cost.toFixed(7)} 0G`);
    totalGas += gasEst;
  }

  const total0G = Number(totalGas * gasPrice) / 1e18;
  console.log(`\n  ${'TOTAL'.padEnd(20)} ${totalGas.toLocaleString().padStart(12)} gas = ${total0G.toFixed(7)} 0G`);

  if (total0G > MAX_GAS_0G) {
    throw new Error(`ABORT: estimated ${total0G.toFixed(6)} 0G exceeds limit of ${MAX_GAS_0G} 0G. Check gas price or optimizer settings.`);
  }
  console.log(`\n✓ Gas estimate within limit (< ${MAX_GAS_0G} 0G). Safe to proceed.\n`);
}

async function main() {
  if (DRY_RUN) { await dryRun(); return; }

  if (network.config.chainId !== 16661) {
    throw new Error('deploy-aristotle is Aristotle-only (chainId 16661). Use --network aristotle.');
  }

  const [deployer] = await ethers.getSigners();
  if (!deployer) throw new Error('DEPLOYER_PRIVATE_KEY is required.');

  const balance = await ethers.provider.getBalance(deployer.address);
  const minBalance = ethers.parseEther('0.5');
  if (balance < minBalance) {
    throw new Error(`Deployer balance ${ethers.formatEther(balance)} 0G < 0.5 0G minimum. Top up before deploying.`);
  }
  console.log(`\nDeploying to Aristotle from ${deployer.address} (balance: ${ethers.formatEther(balance)} 0G)\n`);

  const records: DeploymentRecord[] = [];
  const deployed: Array<{ record: DeploymentRecord; args: readonly unknown[] }> = [];

  const add = (result: { record: DeploymentRecord; args: readonly unknown[] }) => {
    records.push(result.record);
    deployed.push(result);
  };

  const policy      = await deploy('PolicyEngine',    [deployer.address]);                                                          add(policy);
  const receiptBook = await deploy('ReceiptBook',     [deployer.address]);                                                          add(receiptBook);
  const identity    = await deploy('AgentIdentity',   [deployer.address]);                                                          add(identity);
  const registry    = await deploy('ServiceRegistry', [deployer.address]);                                                          add(registry);
  const splitter    = await deploy('RevenueSplitter', [deployer.address]);                                                          add(splitter);
  const router      = await deploy('PaymentRouter',   [deployer.address, receiptBook.record.address, splitter.record.address]);     add(router);
  const escrow      = await deploy('EscrowVault',     [deployer.address, receiptBook.record.address]);                              add(escrow);
  const factory     = await deploy('AccountFactory',  [deployer.address, policy.record.address, receiptBook.record.address]);       add(factory);

  const rb = await ethers.getContractAt('ReceiptBook', receiptBook.record.address);
  for (const relayer of [identity.record.address, registry.record.address, router.record.address, escrow.record.address, factory.record.address]) {
    await (await rb.authoriseRelayer(relayer)).wait(2);
  }
  if (process.env.RECEIPT_RELAYER) await (await rb.authoriseRelayer(process.env.RECEIPT_RELAYER)).wait(2);
  console.log('  ✓ Relayers authorised');

  const af = await ethers.getContractAt('AccountFactory', factory.record.address);
  const salt = ethers.id('apogee-genesis-agent');
  const predicted = await af.predict(deployer.address, salt);
  const createReceipt = await (await af.createAccount(deployer.address, salt)).wait(2);
  if (!createReceipt) throw new Error('Missing AgentAccount creation receipt.');
  const agentRecord: DeploymentRecord = { name: 'AgentAccount', address: predicted, txHash: createReceipt.hash, blockNumber: createReceipt.blockNumber, verified: false };
  records.push(agentRecord);
  deployed.push({ record: agentRecord, args: [deployer.address, policy.record.address, receiptBook.record.address, 1, [deployer.address, deployer.address, deployer.address]] });
  await (await rb.authoriseRelayer(predicted)).wait(2);
  console.log(`  ✓ AgentAccount: ${predicted}`);

  console.log('\nVerifying on chainscan.0g.ai…');
  for (const item of deployed) {
    const updated = await verify(item.record, item.args);
    const idx = records.findIndex(r => r.address === updated.address);
    if (idx >= 0) records[idx] = updated;
  }

  const outDir = join(process.cwd(), 'deployments');
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'aristotle.json'), `${JSON.stringify(records, null, 2)}\n`);
  console.log('\n  ✓ Wrote deployments/aristotle.json');

  await writeContractsLib(records);

  const verified = records.filter(r => r.verified).length;
  console.log(`\n=== Aristotle deploy complete — ${verified}/${records.length} verified ===`);
  console.log(JSON.stringify(records, null, 2));
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
